# Generated by Django 3.1.7 on 2023-04-24 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 19, 16, 13, 556089)),
        ),
    ]
