# Generated by Django 4.2 on 2023-04-25 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quesmodel_alter_category_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 21, 8, 10, 307443)),
        ),
    ]
