# Generated by Django 4.2 on 2023-04-25 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_history_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='history',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 22, 28, 22, 296280)),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='ans',
            field=models.CharField(max_length=200, null=True, verbose_name='дұрыс жауап: option1/2/3 болмаса option4'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op1',
            field=models.CharField(max_length=200, null=True, verbose_name='Сұрақ: option1'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op2',
            field=models.CharField(max_length=200, null=True, verbose_name='Сұрақ: option2'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op3',
            field=models.CharField(max_length=200, null=True, verbose_name='Сұрақ: option3'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op4',
            field=models.CharField(max_length=200, null=True, verbose_name='Сұрақ: option4'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=200, null=True, verbose_name='Сұрақ: '),
        ),
    ]
